version: '3.7'
services:
  nginx:
    image: nginx:1.17
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/app/screendisplay:/www/screendisplay:rw
    tty: true
    ports:
      - 8440:80
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgres@127.0.0.1:5432/postgres'

volumes:
  db-data:
