version: '3.7'
services:
  nginx:
    image: nginx:1.17
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/app/screendisplay:/www/screendisplay:rw
      - ./backend/app/webapp/static:/www/static:rw
    tty: true
    ports:
      - 8440:80
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: '${DATABASE_URL}'
      GRAPH_CLIENT_ID: '${GRAPH_CLIENT_ID}'
      GRAPH_CLIENT_SECRET: '${GRAPH_CLIENT_SECRET}'
      GRAPH_AUTHORITY: '${GRAPH_AUTHORITY}'
      SECRET_KEY: '19d25e094faa6ca2556c811166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7'

volumes:
  db-data:
