steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME
      - '--file'
      - ./backend/Dockerfile
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME']
    id: Push image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['run', 'deploy', '$_CLOUDRUN_RESOURCE_NAME', '--image', 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
    id: Deploy
    entrypoint: gcloud

images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_BASENAME-cr-$BRANCH_NAME'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'europe-west1'                   # cloud run region - ensure all services are in the same region to avoid latency and to allow for internal networking
  _IMAGE_REPO: 'gcr.io'
  _IMAGE_BASENAME: 'webook-api'
  _CLOUDRUN_RESOURCE_NAME: 'webook-api-dev' # resultant resource name of cloud run service
  _ENV_IDENTIFIER: 'dev'                    # dev, staging, prod - use this to switch between secrets
